#!/usr/bin/php
<?php
 
require 'lib/xdg.php';
require 'lib/sys.php';

$desktop_path = '/usr/share/app-install/desktop/';
$data_path = '../data/';




// Icons
foreach(glob('/usr/share/app-install/icons/*') as $file) {
    $info = pathinfo($file);
    if($info['extension']=='xpm') {
        echo "Converting $file\n";
         exec( "convert $file ../data/icons/$info[filename].png");
    } else {
        
        echo "Copying $file\n";
        copy($file,'../data/icons/'. basename($file));
    }
}


// Desktop file list
echo "Generating packages.json...\n";
$data = Xdg::parse_desktop_folder($desktop_path);
$json = json_encode($data);
$json = str_replace('},{', "},\n{", $json);
file_put_contents($data_path . 'packages.json', $json);
file_put_contents($data_path . 'packages.js', 'var packages = ' . $json . ';');

echo "Generating installed.json...\n";
$installed = Sys::installed();
$json_installed = json_encode($installed);
file_put_contents($data_path . 'installed.json', $json_installed);
file_put_contents($data_path . 'installed.js', 'var installed = ' . $json_installed . ';');



$total = count($data);
$count = 0;
foreach($data as $pkg) {
    ++$count;
    echo str_pad("Generating packages/$pkg[package].json", 70) . "$count/$total\n";
    $json = json_encode(Sys::info($pkg['package']));
    $json = str_replace('","', "\",\n \"", $json);
    file_put_contents($data_path . 'packages/' . $pkg['package'] . '.json', $json);
}

echo "Done.";




